import {useEffect,useState} from 'react';
import {request} from '../api/client';
import {MICRO_FEED_LEVELS,archiveMicroFeedItem,type MicroFeedItem} from '../api/microFeed';
import {Button} from './ui';

export function AdminVideos(){
 const [items,setItems]=useState<MicroFeedItem[]>([]),[url,setUrl]=useState(''),[category,setCategory]=useState('culture'),[cefr,setCefr]=useState('B1'),[tags,setTags]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setItems((await request<{items:MicroFeedItem[]}>('/v1/admin/micro-videos')).items);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить видео.');}}
 useEffect(()=>{void load();},[]);
 async function add(){if(busy)return;setBusy(true);setError('');try{await request('/v1/admin/micro-videos',{method:'POST',body:{url,category,cefr,tags:tags.split(',').map(s=>s.trim()).filter(Boolean)}});setUrl('');await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось добавить ролик.');}finally{setBusy(false);}}
 return <section className="mb-8 rounded-2xl border border-[var(--line)] bg-[var(--bg-raised)] p-5"><h2 className="text-2xl font-bold">Видео Вукотока</h2><p className="my-3 text-[var(--text-muted)]">Ключ YouTube не нужен. Добавь ссылку, посмотри ролик и подтверди сербскую речь. Наличие сербских титров недостаточно.</p>{error&&<p role="alert">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><label>Ссылка YouTube<input className="answer-input" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.youtube.com/shorts/…"/></label><label>Тема<select className="answer-input" value={category} onChange={e=>setCategory(e.target.value)}>{['culture','history','science','society','news','fiction','food','travel','sport','music','language'].map(c=><option key={c}>{c}</option>)}</select></label><label>Уровень<select className="answer-input" value={cefr} onChange={e=>setCefr(e.target.value)}>{MICRO_FEED_LEVELS.map(c=><option key={c}>{c}</option>)}</select></label><label>Теги через запятую<input className="answer-input" value={tags} onChange={e=>setTags(e.target.value)}/></label></div><Button className="mt-3" disabled={busy||!url.trim()} onClick={()=>void add()}>Добавить на проверку</Button>
 <div className="mt-5 grid gap-4">{items.map(item=><VideoReview key={`${item.id}:${item.status}`} item={item} refresh={load}/>)}</div></section>;
}
function VideoReview({item,refresh}:{item:MicroFeedItem;refresh:()=>Promise<void>}){
 const [speech,setSpeech]=useState(false),[embed,setEmbed]=useState(false),[seconds,setSeconds]=useState(item.videoDuration||60),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false);
 async function publish(){setBusy(true);try{await request(`/v1/admin/micro-videos/${item.id}/publish`,{method:'POST',body:{serbianSpeech:speech,embeddingChecked:embed,duration:seconds}});await refresh();}catch(e){setError(e instanceof Error?e.message:'Не удалось опубликовать.');}finally{setBusy(false);}}
 return <article className="rounded-xl border border-[var(--line)] p-4"><h3 className="font-bold">{item.titleLatin}</h3><p>{item.sourceTitle} · {item.cefr} · {item.status}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="underline">Оригинал</a><Button className="m-2" variant="secondary" onClick={()=>setPreview(!preview)}>{preview?'Закрыть плеер':'Проверить встраивание'}</Button>{preview&&<iframe src={`/video-player.html?v=${item.videoId}`} title={item.titleLatin} className="h-80 w-full" allow="autoplay; encrypted-media; fullscreen" allowFullScreen/>}{item.status!=='published'&&<><label className="my-3 block"><input type="checkbox" checked={speech} onChange={e=>setSpeech(e.target.checked)}/> Я прослушал ролик: речь на сербском</label><label className="my-3 block"><input type="checkbox" checked={embed} onChange={e=>setEmbed(e.target.checked)}/> Встроенный плеер воспроизводит видео</label><label>Длительность, секунды<input type="number" min={1} max={180} className="answer-input max-w-40" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/></label><Button className="mt-3" disabled={busy||!speech||!embed||seconds<1||seconds>180} onClick={()=>void publish()}>Опубликовать</Button></>}{item.status==='published'&&<Button variant="secondary" disabled={busy} onClick={()=>{setBusy(true);void archiveMicroFeedItem(item.id).then(refresh).catch(()=>setError('Не удалось скрыть видео.')).finally(()=>setBusy(false));}}>Скрыть видео</Button>}{error&&<p role="alert">{error}</p>}</article>;
}
